config/routes.rb
Rails.application.routes.draw do
  resources :solvents

  get 'pages/info'

  resources :reagents
  root :to => redirect('/reagents')

end

app/models/reagent.rb
class Reagent < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/models/solvent.rb
class Solvent < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/controllers/reagents_controller.rb
class ReagentsController < ApplicationController
  before_action :set_reagent, only: [:show, :edit, :update, :destroy]

  # GET /reagents
  # GET /reagents.json
  def index
    @reagents = Reagent.all
  end

  # GET /reagents/1
  # GET /reagents/1.json
  def show
  end

  # GET /reagents/new
  def new
    @reagent = Reagent.new
  end

  # GET /reagents/1/edit
  def edit
  end

  # POST /reagents
  # POST /reagents.json
  def create
    @reagent = Reagent.new(reagent_params)

    respond_to do |format|
      if @reagent.save
        format.html { redirect_to @reagent, notice: 'Reagent was successfully created.' }
        format.json { render :show, status: :created, location: @reagent }
      else
        format.html { render :new }
        format.json { render json: @reagent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reagents/1
  # PATCH/PUT /reagents/1.json
  def update
    respond_to do |format|
      if @reagent.update(reagent_params)
        format.html { redirect_to @reagent, notice: 'Reagent was successfully updated.' }
        format.json { render :show, status: :ok, location: @reagent }
      else
        format.html { render :edit }
        format.json { render json: @reagent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reagents/1
  # DELETE /reagents/1.json
  def destroy
    @reagent.destroy
    respond_to do |format|
      format.html { redirect_to reagents_url, notice: 'Reagent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reagent
      @reagent = Reagent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reagent_params
      params.require(:reagent).permit(:name, :picture, :trait_1, :trait_2, :trait_3, :trait_4)
    end
end

app/controllers/solvents_controller.rb
class SolventsController < ApplicationController
  before_action :set_solvent, only: [:show, :edit, :update, :destroy]

  # GET /solvents
  # GET /solvents.json
  def index
    @solvents = Solvent.all
  end

  # GET /solvents/1
  # GET /solvents/1.json
  def show
  end

  # GET /solvents/new
  def new
    @solvent = Solvent.new
  end

  # GET /solvents/1/edit
  def edit
  end

  # POST /solvents
  # POST /solvents.json
  def create
    @solvent = Solvent.new(solvent_params)

    respond_to do |format|
      if @solvent.save
        format.html { redirect_to @solvent, notice: 'Solvent was successfully created.' }
        format.json { render :show, status: :created, location: @solvent }
      else
        format.html { render :new }
        format.json { render json: @solvent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /solvents/1
  # PATCH/PUT /solvents/1.json
  def update
    respond_to do |format|
      if @solvent.update(solvent_params)
        format.html { redirect_to @solvent, notice: 'Solvent was successfully updated.' }
        format.json { render :show, status: :ok, location: @solvent }
      else
        format.html { render :edit }
        format.json { render json: @solvent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solvents/1
  # DELETE /solvents/1.json
  def destroy
    @solvent.destroy
    respond_to do |format|
      format.html { redirect_to solvents_url, notice: 'Solvent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_solvent
      @solvent = Solvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def solvent_params
      params.require(:solvent).permit(:name, :picture, :level)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reagents_helper.rb
module ReagentsHelper
end

app/helpers/solvents_helper.rb
module SolventsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alchemy</title>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css" />
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">The Alchemy App</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/reagents">Reagents</a></li>
          <li class="active"><a href="/solvents">Solvents</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

  <footer>
    <div class="container">
      ESO Alchemy 2014
    </div>
  </footer>
  <script src="//railsgirls.com/assets/bootstrap.js"></script>

</body>
</html>

app/views/pages/info.html.erb
<h1>About the author:</h1>
<p>Dad, friend of pandas, automation enthusiast, and Ruby Master wanna-be!</p>

app/views/reagents/_form.html.erb
<%= form_for(@reagent) do |f| %>
  <% if @reagent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reagent.errors.count, "error") %> prohibited this reagent from being saved:</h2>

      <ul>
      <% @reagent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :trait_1 %><br>
    <%= f.text_field :trait_1 %>
  </div>
  <div class="field">
    <%= f.label :trait_2 %><br>
    <%= f.text_field :trait_2 %>
  </div>
  <div class="field">
    <%= f.label :trait_3 %><br>
    <%= f.text_field :trait_3 %>
  </div>
  <div class="field">
    <%= f.label :trait_4 %><br>
    <%= f.text_field :trait_4 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reagents/edit.html.erb
<h1>Editing reagent</h1>

<%= render 'form' %>

<%= link_to 'Show', @reagent %> |
<%= link_to 'Back', reagents_path %>

app/views/reagents/index.html.erb
<h1>Listing reagents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Picture</th>
      <th>Trait 1</th>
      <th>Trait 2</th>
      <th>Trait 3</th>
      <th>Trait 4</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reagents.each do |reagent| %>
      <tr>
        <td><%= reagent.name %></td>
        <td><%= image_tag(reagent.picture_url, :width => 200) if reagent.picture.present? %></td>
        <td><%= reagent.trait_1 %></td>
        <td><%= reagent.trait_2 %></td>
        <td><%= reagent.trait_3 %></td>
        <td><%= reagent.trait_4 %></td>
        <td><%= link_to 'Show', reagent %></td>
        <td><%= link_to 'Edit', edit_reagent_path(reagent) %></td>
        <td><%= link_to 'Destroy', reagent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reagent', new_reagent_path %>

app/views/reagents/new.html.erb
<h1>New reagent</h1>

<%= render 'form' %>

<%= link_to 'Back', reagents_path %>

app/views/reagents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reagent.name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@reagent.picture_url, :width => 200) if @reagent.picture.present? %>
</p>

<p>
  <strong>Trait 1:</strong>
  <%= @reagent.trait_1 %>
</p>

<p>
  <strong>Trait 2:</strong>
  <%= @reagent.trait_2 %>
</p>

<p>
  <strong>Trait 3:</strong>
  <%= @reagent.trait_3 %>
</p>

<p>
  <strong>Trait 4:</strong>
  <%= @reagent.trait_4 %>
</p>

<%= link_to 'Edit', edit_reagent_path(@reagent) %> |
<%= link_to 'Back', reagents_path %>

app/views/solvents/_form.html.erb
<%= form_for(@solvent) do |f| %>
  <% if @solvent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@solvent.errors.count, "error") %> prohibited this solvent from being saved:</h2>

      <ul>
      <% @solvent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.text_field :level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/solvents/edit.html.erb
<h1>Editing solvent</h1>

<%= render 'form' %>

<%= link_to 'Show', @solvent %> |
<%= link_to 'Back', solvents_path %>

app/views/solvents/index.html.erb
<h1>Listing solvents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Picture</th>
      <th>Level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @solvents.each do |solvent| %>
      <tr>
        <td><%= solvent.name %></td>
        <td><%= image_tag(solvent.picture_url, :width => 200) if solvent.picture.present? %></td>
        <td><%= solvent.level %></td>
        <td><%= link_to 'Show', solvent %></td>
        <td><%= link_to 'Edit', edit_solvent_path(solvent) %></td>
        <td><%= link_to 'Destroy', solvent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Solvent', new_solvent_path %>

app/views/solvents/new.html.erb
<h1>New solvent</h1>

<%= render 'form' %>

<%= link_to 'Back', solvents_path %>

app/views/solvents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @solvent.name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@solvent.picture_url, :width => 200) if @solvent.picture.present? %>
</p>

<p>
  <strong>Level:</strong>
  <%= @solvent.level %>
</p>

<%= link_to 'Edit', edit_solvent_path(@solvent) %> |
<%= link_to 'Back', solvents_path %>